DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS list_user;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS movie;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL
);

CREATE TABLE list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_by INTEGER NOT NULL,
  FOREIGN KEY (created_by) REFERENCES user (id)
);

CREATE TABLE list_user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  list_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  can_edit BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY (list_id) REFERENCES list (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE genre (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE movie (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  watched BOOLEAN NOT NULL DEFAULT 0,
  genre_id INTEGER NOT NULL,
  list_id INTEGER NOT NULL,
  added_by INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (genre_id) REFERENCES genre (id),
  FOREIGN KEY (list_id) REFERENCES list (id),
  FOREIGN KEY (added_by) REFERENCES user (id)
);
